spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
    username: root
    password: MTIzNDU2
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      filters: stat,wall
      filter:
        stat:
          enabled: true #开启监控页面功能
        wall:
          enabled: true #开启sql防火墙功能
          config:
            drop-table-allow: false #禁止删表操作
      stat-view-servlet:
        enabled: true
        login-username: admin #Druid监控页面登录账号
        login-password: admin #Druid监控页面登录密码
      web-stat-filter:
        enabled: true #开启请求过滤器
        url-pattern: /* #过滤所有请求
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*' #放行的请求
      aop-patterns: com.zhangqiang.learn.* #开启Druid数据源监控页面spring监控功能
  redis:
    port: 6379
    password: 123456
    host: localhost
#配置mybatis的全局配置文件路径地址和mapper文件地址
mybatis-plus:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  #开启驼峰命名匹配
  configuration: #这个配置下的属性可以代替mybatis全局配置文件的属性
    map-underscore-to-camel-case: true
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
      show-details: always #总是显示详细信息。可显示每个模块的状态信息